# Production manifest. Remove image locally to build from the Dockerfile.
name: YouTube to Media
version: "0.2.0"
slug: youtube-to-media
description: Download YouTube media to Home Assistant shared storage.
url: "https://github.com/Schroedingberg/ha-yt-cache/tree/main/youtube-to-media"
image: "ghcr.io/schroedingberg/youtube-to-media"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
map:
  - share:rw
ingress: true
panel_icon: mdi:youtube
panel_title: YouTube to Media
